In [13]:
import pandas as pd
import numpy as np

In [14]:
# 데이터 불러오기, 시계열데이터로 변환

df=pd.read_csv('BIT_2023_1차.csv')
df.set_index('time', inplace=True)
df.index=pd.to_datetime(df.index)
df

,Open,High,Low,Close,Volume,returns,volatility,price,quote_qty,is_buyer_maker,quote_qty_cal
time,,,,,,,,,,,
2023-01-01 00:00:00,16537.5,16540.9,16504.0,16527.0,5381.399,NaN,NaN,16524.525741,7264.129209,16494,8.892507e+07
2023-01-01 01:00:00,16527.1,16554.3,16524.1,16550.4,3210.826,0.001416,NaN,16537.215985,6819.889969,8705,5.309812e+07
2023-01-01 02:00:00,16550.5,16557.1,16534.8,16542.4,2399.668,-0.000483,NaN,16545.818136,6030.420093,8468,3.970447e+07
2023-01-01 03:00:00,16542.5,16542.5,16515.0,16529.3,3214.480,-0.000792,NaN,16525.582085,7003.352799,10007,5.312115e+07
2023-01-01 04:00:00,16529.2,16530.4,16508.8,16517.8,3150.954,-0.000696,NaN,16518.286421,7378.899423,9476,5.204836e+07
...,...,...,...,...,...,...,...,...,...,...,...
2023-12-31 19:00:00,42701.7,42741.9,42624.7,42659.9,3944.096,-0.000977,0.003040,42679.290530,14458.392200,23305,1.683312e+08
2023-12-31 20:00:00,42659.9,42724.5,42543.3,42599.1,4730.936,-0.001425,0.002863,42625.853600,12326.119420,28014,2.016602e+08
2023-12-31 21:00:00,42599.2,42717.0,42558.2,42558.9,3794.010,-0.000944,0.002673,42634.523520,13367.479780,21732,1.617558e+08
2023-12-31 22:00:00,42559.0,42629.5,42111.9,42294.8,11952.346,-0.006206,0.003008,42405.779790,19111.648040,67159,5.068486e+08
2023-12-31 23:00:00,42294.8,42380.1,42083.1,42314.0,11676.465,0.000454,0.002975,42244.204650,16705.045390,58180,4.932630e+08

In [15]:
# MACD 함수

def MACD(df, short_window, long_window, signal_window):
    
    df[f'Short_MA_{short_window}'] = df['Close'].ewm(span=short_window, adjust=False).mean()
    df[f'Long_MA_{long_window}'] = df['Close'].ewm(span=long_window, adjust=False).mean()
    df[f'MACD_{short_window}{long_window}'] = df[f'Short_MA_{short_window}'] - df[f'Long_MA_{long_window}']
    df[f'Signal_Line_{signal_window}'] = df[f'MACD_{short_window}{long_window}'].ewm(span=signal_window, adjust=False).mean()
    df[f'MACD_Oscillator{short_window}{long_window}'] = df[f'MACD_{short_window}{long_window}'] - df[f'Signal_Line_{signal_window}']
    
MACD(df, 6, 13, 4) #단기추세 감지 but 노이즈에 민감할 가능성 있음
MACD(df, 12, 26, 9) #일반적인 window 계수 but 변동성이 큰 시장에선 느리게 반응할 수 있음

df

,Open,High,Low,Close,Volume,returns,volatility,price,quote_qty,is_buyer_maker,...,Short_MA_6,Long_MA_13,MACD_613,Signal_Line_4,MACD_Oscillator613,Short_MA_12,Long_MA_26,MACD_1226,Signal_Line_9,MACD_Oscillator1226
time,,,,,,,,,,,,,,,,,,,,,
2023-01-01 00:00:00,16537.5,16540.9,16504.0,16527.0,5381.399,NaN,NaN,16524.525741,7264.129209,16494,...,16527.000000,16527.000000,0.000000,0.000000,0.000000,16527.000000,16527.000000,0.000000,0.000000,0.000000
2023-01-01 01:00:00,16527.1,16554.3,16524.1,16550.4,3210.826,0.001416,NaN,16537.215985,6819.889969,8705,...,16533.685714,16530.342857,3.342857,1.337143,2.005714,16530.600000,16528.733333,1.866667,0.373333,1.493333
2023-01-01 02:00:00,16550.5,16557.1,16534.8,16542.4,2399.668,-0.000483,NaN,16545.818136,6030.420093,8468,...,16536.175510,16532.065306,4.110204,2.446367,1.663837,16532.415385,16529.745679,2.669706,0.832608,1.837098
2023-01-01 03:00:00,16542.5,16542.5,16515.0,16529.3,3214.480,-0.000792,NaN,16525.582085,7003.352799,10007,...,16534.211079,16531.670262,2.540816,2.484147,0.056669,16531.936095,16529.712666,2.223429,1.110772,1.112657
2023-01-01 04:00:00,16529.2,16530.4,16508.8,16517.8,3150.954,-0.000696,NaN,16518.286421,7378.899423,9476,...,16529.522199,16529.688796,-0.166597,1.423849,-1.590447,16529.761311,16528.830246,0.931065,1.074831,-0.143766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-31 19:00:00,42701.7,42741.9,42624.7,42659.9,3944.096,-0.000977,0.003040,42679.290530,14458.392200,23305,...,42628.093679,42562.493868,65.599811,64.108792,1.491019,42571.593935,42468.781019,102.812915,89.759614,13.053302
2023-12-31 20:00:00,42659.9,42724.5,42543.3,42599.1,4730.936,-0.001425,0.002863,42625.853600,12326.119420,28014,...,42619.809771,42567.723316,52.086455,59.299857,-7.213402,42575.825637,42478.434277,97.391360,91.285963,6.105397
2023-12-31 21:00:00,42599.2,42717.0,42558.2,42558.9,3794.010,-0.000944,0.002673,42634.523520,13367.479780,21732,...,42602.406979,42566.462842,35.944137,49.957569,-14.013432,42573.221693,42484.394701,88.826992,90.794169,-1.967177
2023-12-31 22:00:00,42559.0,42629.5,42111.9,42294.8,11952.346,-0.006206,0.003008,42405.779790,19111.648040,67159,...,42514.519271,42527.653864,-13.134594,24.720704,-37.855298,42530.387586,42470.350649,60.036937,84.642722,-24.605785
2023-12-31 23:00:00,42294.8,42380.1,42083.1,42314.0,11676.465,0.000454,0.002975,42244.204650,16705.045390,58180,...,42457.228051,42497.131884,-39.903833,-1.129111,-38.774722,42497.097188,42458.769119,38.328069,75.379792,-37.051723

In [9]:
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'returns', 'volatility',
       'price', 'quote_qty', 'is_buyer_maker', 'quote_qty_cal', 'Short_MA_6',
       'Long_MA_13', 'MACD_613', 'Signal_Line_4', 'MACD_Oscillator613',
       'Short_MA_12', 'Long_MA_26', 'MACD_1226', 'Signal_Line_9',
       'MACD_Oscillator1226'],
      dtype='object')

In [11]:
# 필요한 컬럼만 남기고 drop
# MACD_613, Signal_Line_4, MACD_Oscillator613
# MACD_1226, Signal_Line_9, MACD_Oscillator1226

df_MACD=df.drop(['Open', 'High', 'Low', 'Close', 'Volume', 'returns', 'volatility',
       'price', 'quote_qty', 'is_buyer_maker', 'quote_qty_cal', 'Short_MA_6',
       'Long_MA_13','Short_MA_12', 'Long_MA_26' ], axis=1)
df_MACD

,MACD_613,Signal_Line_4,MACD_Oscillator613,MACD_1226,Signal_Line_9,MACD_Oscillator1226
time,,,,,,
2023-01-01 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2023-01-01 01:00:00,3.342857,1.337143,2.005714,1.866667,0.373333,1.493333
2023-01-01 02:00:00,4.110204,2.446367,1.663837,2.669706,0.832608,1.837098
2023-01-01 03:00:00,2.540816,2.484147,0.056669,2.223429,1.110772,1.112657
2023-01-01 04:00:00,-0.166597,1.423849,-1.590447,0.931065,1.074831,-0.143766
...,...,...,...,...,...,...
2023-12-31 19:00:00,65.599811,64.108792,1.491019,102.812915,89.759614,13.053302
2023-12-31 20:00:00,52.086455,59.299857,-7.213402,97.391360,91.285963,6.105397
2023-12-31 21:00:00,35.944137,49.957569,-14.013432,88.826992,90.794169,-1.967177
2023-12-31 22:00:00,-13.134594,24.720704,-37.855298,60.036937,84.642722,-24.605785
2023-12-31 23:00:00,-39.903833,-1.129111,-38.774722,38.328069,75.379792,-37.051723

In [12]:
df_MACD.to_csv('BIT_2023_MACD.csv')